### PR TITLE
ci: add windows runner

### PR DESCRIPTION
**Pull request by delta1**
adds windows to CI, which shows a build issue in windows for electrsd

### CODE REVIEW

**Comment by RCasatta** [comment]
@delta1 I released an updated version of electrsd can you retry?

**Comment by delta1** [comment]
@RCasatta thanks! updated - force pushed because I put the wrong version in the commit message

**Comment by LeoComandini** [comment]
utACK cf71cd17510c15dbc5efde33c2ab3df3247aed60, code review

**Comment by RCasatta** [comment]
utACK cf71cd17510c15dbc5efde33c2ab3df3247aed60

**Comment by erustyrannus** [comment]
Tested on Windows 11 using Python 3.12.2:

(lwk-bindings-0.2.0) wheel install 
import lmk
and command:

`str(lwk.Network.mainnet())`

Results:
'Liquid'

**Comment by RCasatta** [comment]
we utacked/merged before the last commit...

utACK 1e9bf6a3bd15ad88af80d90735724d0f933eeeec

**Comment by RCasatta** [comment]
cherry-picked https://github.com/Blockstream/lwk/commit/1e9bf6a3bd15ad88af80d90735724d0f933eeeec

**Comment by delta1** [comment]
> we utacked/merged before the last commit...
> 
> utACK [1e9bf6a](https://github.com/Blockstream/lwk/commit/1e9bf6a3bd15ad88af80d90735724d0f933eeeec)

yep i didn’t see before i pushed as i was busy testing it

**Pull request closed without merging**
