### PR TITLE
Update pset.rs

### PR DESCRIPTION
**Pull request by apotdevin**
Expose `toBase64` from the PSET class

### CODE REVIEW

**Comment by RCasatta** [comment]
Concept ACK, thanks!

I think it's fine to use the canonical `toString()` like we do [here](https://github.com/Blockstream/lwk/blob/6c9dd29a3750ca6c667e3501b6490b60b571b98a/lwk_wasm/src/blockdata/transaction.rs#L61) since it's pretty standard to use base64 for PSETs (as it is hex for transactions)

**Comment by apotdevin** [comment]
Thanks for the pointer! Changed to stay consistent 👍

**Comment by RCasatta** [comment]
Would you please squash the 2 commits into 1?
Thanks

**Comment by apotdevin** [comment]
Done

**Comment by RCasatta** [comment]
utACK 75b68ed2d31298f1ae8fafa993ea49cbcf4a352c

Thanks!

**Pull request merged**
